spring:
  application:
    name: hteos-admin
  profiles:
    active: dev
hteos:
  template-user: demo@hteos.com #模板账号
  image-server: http://asset.hteos.com
---
spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 3571571
    url: jdbc:mysql://localhost:3306/hteos4?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
      hibernate.id.new_generator_mappings: true
---
spring:
  profiles: prod
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://${MYSQL_HOST}:3306/hteos4?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
      hibernate.id.new_generator_mappings: true
